<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\app_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\app_icon.ico" />
    <None Remove="Assets\app_icon.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\app_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Lists\Books\" />
    <Folder Include="Lists\Songs\" />
    <Folder Include="item_Song\Model\" />
    <Folder Include="Modules\Settings\" />
    <Folder Include="Modules\Service\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\app_icon.ico" />
    <Resource Include="Assets\app_icon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
